### ISSUE TITLE
level 4 and bluebird

### ISSUE THREAD

**Issue by timofei7** [irenelfeng/boomsync#9]
i think it'd be helpful to show what a promise really is more like:

```js
const promiseThrow = new Promise((resolve,reject) => {
    throwBoomerang((error, result)=>{
        if (error) {
            reject(error);
        } else {
            resolve(result);
        }
    });
});
promiseThrow().then(() => throwBoomerang());
```

perhaps first without the error and to illustrate just the callback, then with fairly standard error,result callback args.    bluebird just does some magic and its hard to comprehend what the promise is without constructing one from scratch.    granted when i try this it yells at me promiseThrow isn't a function, but haven't dug into it yet.

**Comment by timofei7** [comment]
ah interesting,  looks like

```js
const promiseThrow = () => { return new Promise((resolve,reject) => {
    throwBoomerang((error, result)=>{
        if (error) {
            reject(error);
        } else {
            resolve(result);
        }
    });
})};
promiseThrow().then(() => {
    throwBoomerang(() => { console.log('once more')});
}).catch(error => {
    console.log(error);
});
```

kindof works - the second throw is called but much later, seems to be setting the time to initial wait time and then not drawing

**Comment by irenelfeng** [comment]
Fixed it up, I think the playing component unmounted once the promise is
fulfilled because it thought there are no boomerangs left to throw. Fixed
some logic there. Can you test all the levels again? and then I can add
making of promises before Bluebird.

**Comment by timofei7** [comment]
cool!   seems to work! 

it'd be great if just doing:
```js
const promiseThrow =  new Promise(... 
```
worked rather than:
```js
const promiseThrow = () => { return new Promise(...
```
